### ISSUE TITLE
想问一下TS版的文档有适用于生产环境的吗？

### ISSUE THREAD

**Issue by ghost** [blinker-iot/blinker-js#12]
比如从开发到部署怎么搞，还有写组件的使用方法，对应有哪些API什么的，从现在的文档看有点一头雾水。。。

**Comment by coloz** [comment]
API文档：
https://diandeng.tech/doc/javascript-support
使用方法文档配合本仓库中的examples。

部署和node程序没有区别，建议配合pm2
