### ISSUE TITLE
文档中的这行代码似乎出现了编码错误

### ISSUE THREAD

**Issue by conglinyizhi** [blinker-iot/blinker-js#21]
https://github.com/blinker-iot/blinker-js/blob/e6431ae05f7c3a3a9ebc60b629f427039ed12855/example/readme.md?plain=1#L8

如果是编码错误希望及时修复

**Comment by coloz** [comment]
这是界面配置，需要在设备设置》界面配置中导入，且也测试了，导入是没有问题的。

**Comment by coloz** [comment]
这是界面配置，需要在设备设置》界面配置中导入，且也测试了，导入是没有问题的。

**Comment by conglinyizhi** [comment]
好的，感谢回复
